### ISSUE TITLE
Error while running .fit on the PaliGemma example from Kaggle

### ISSUE THREAD

**Issue by arrufat** [keras-team/keras-nlp#1648]
**Describe the bug**

**To Reproduce**

I am running out of RAM in Colab, so I'll just post the script here, adapted from https://www.kaggle.com/models/keras/paligemma/keras/pali_gemma_3b_224.

This is the code I run, using the latest keras-nlp:
```py
import io
import json
import os

import numpy as np
import PIL
import requests

os.environ["KERAS_BACKEND"] = "jax"
import keras  # noqa: E402
import keras_nlp  # noqa: E402


def read_image(url):
    contents = io.BytesIO(requests.get(url).content)
    image = PIL.Image.open(contents)
    image = np.array(image)
    # Remove alpha channel if neccessary.
    if image.shape[2] == 4:
        image = image[:, :, :3]
    # Scale to range [0, 1].
    return image / 127.5 - 1


with open("kaggle.json", "r") as f:
    contents = json.load(f)
    os.environ["KAGGLE_USERNAME"] = contents["username"]
    os.environ["KAGGLE_KEY"] = contents["key"]

keras.config.set_floatx("bfloat16")
pali_gemma_lm = keras_nlp.models.PaliGemmaCausalLM.from_preset("pali_gemma_3b_224")
image_url = "https://storage.googleapis.com/keras-cv/models/paligemma/cow_beach_1.png"
image = read_image(image_url)

prompts = [
    "answer en where is the cow standing?\n",
    "answer en what color is the cow?\n",
    "describe en\n",
    "detect cow\n",
    "segment cow\n",
]
images = [image, image, image, image, image]
outputs = pali_gemma_lm.generate(
    inputs={
        "images": images,
        "prompts": prompts,
    }
)
for output in outputs:
    print(output)


x = {
    "images": [image, image],
    "prompts": ["answer en Where is the cow standing?\n", "caption en\n"],
}
y = {
    "responses": ["beach", "A brown cow standing on a beach next to the ocean."],
}
pali_gemma_lm.fit(x=x, y=y, batch_size=2)
```

And here's the output:
```
2024-05-23 09:03:31.158159: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Downloading from https://www.kaggle.com/api/v1/models/keras/paligemma/keras/pali_gemma_3b_224/1/download/task.json...
Downloading from https://www.kaggle.com/api/v1/models/keras/paligemma/keras/pali_gemma_3b_224/1/download/preprocessor.json...
2024-05-23 09:03:36.984276: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
2024-05-23 09:03:37.434822: E tensorflow/core/util/util.cc:131] oneDNN supports DT_INT64 only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.
WARNING:absl:`PaliGemmaCausalLMPreprocessor` generates `y` and `sample_weight` based on your input data, but your data already contains `y` or `sample_weight`. Your `y` and `sample_weight` will be ignored.
answer en where is the cow standing?
beach
answer en what color is the cow?
red
describe en
A cow on the beach
detect cow
<loc0274><loc0000><loc1022><loc0691> cow
segment cow
<loc0279><loc0000><loc0957><loc0691> <seg014><seg039><seg092><seg116><seg007><seg055><seg089><seg062><seg005><seg121><seg060><seg121><seg016><seg118><seg019><seg068> cow
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    pali_gemma_lm.fit(x=x, y=y, batch_size=2)
  File ".venv/lib/python3.10/site-packages/keras_nlp/src/utils/pipeline_model.py", line 181, in fit
    x = x.map(
  File ".venv/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2299, in map
    return map_op._map_v2(
  File ".venv/lib/python3.10/site-packages/tensorflow/python/data/ops/map_op.py", line 40, in _map_v2
    return _ParallelMapDataset(
  File ".venv/lib/python3.10/site-packages/tensorflow/python/data/ops/map_op.py", line 148, in __init__
    self._map_func = structured_function.StructuredFunctionWrapper(
  File ".venv/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 265, in __init__
    self._function = fn_factory()
  File ".venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 1251, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 1221, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 696, in _initialize
    self._concrete_variable_creation_fn = tracing_compilation.trace_function(
  File ".venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 178, in trace_function
    concrete_function = _maybe_define_function(
  File ".venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 283, in _maybe_define_function
    concrete_function = _create_concrete_function(
  File ".venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 310, in _create_concrete_function
    traced_func_graph = func_graph_module.func_graph_from_py_func(
  File ".venv/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1059, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 599, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 231, in wrapped_fn
    ret = wrapper_helper(*args)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 161, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 693, in wrapper
    raise e.ag_error_metadata.to_exception(e)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 690, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_fileo2p2pemm.py", line 36, in tf__preprocess_samples
    ag__.if_stmt(ag__.ld(self).preprocessor is not None, if_body, else_body, get_state, set_state, ('do_return', 'retval_'), 2)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 1217, in if_stmt
    _py_if_stmt(cond, body, orelse)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/autograph/operators/control_flow.py", line 1270, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/__autograph_generated_fileo2p2pemm.py", line 23, in if_body
    retval_ = ag__.converted_call(ag__.ld(self).preprocessor, (ag__.ld(x),), dict(y=ag__.ld(y), sample_weight=ag__.ld(sample_weight)), fscope)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_file7o6hrad6.py", line 12, in tf____call__
    outputs = ag__.converted_call(ag__.converted_call(ag__.ld(super), (), None, fscope).__call__, tuple(ag__.ld(args)), dict(**ag__.ld(kwargs)), fscope)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File ".venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 459, in _call_unconverted
    return f(*args, **kwargs)
  File ".venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File ".venv/lib/python3.10/site-packages/keras_nlp/src/models/pali_gemma/pali_gemma_causal_lm_preprocessor.py", line 85, in call
    images, prompts, responses = x["images"], x["prompts"], x["responses"]
tensorflow.python.autograph.pyct.error_utils.MultilineMessageKeyError: in user code:

    File ".venv/lib/python3.10/site-packages/keras_nlp/src/models/task.py", line 98, in preprocess_samples  *
        return self.preprocessor(x, y=y, sample_weight=sample_weight)
    File ".venv/lib/python3.10/site-packages/keras_nlp/src/layers/preprocessing/preprocessing_layer.py", line 49, in __call__  *
        outputs = super().__call__(*args, **kwargs)
    File ".venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler  **
        raise e.with_traceback(filtered_tb) from None
    File ".venv/lib/python3.10/site-packages/keras_nlp/src/models/pali_gemma/pali_gemma_causal_lm_preprocessor.py", line 85, in call
        images, prompts, responses = x["images"], x["prompts"], x["responses"]

    KeyError: 'Exception encountered when calling PaliGemmaCausalLMPreprocessor.call().\n\n\x1b[1mresponses\x1b[0m\n\nArguments received by PaliGemmaCausalLMPreprocessor.call():\n  • x={\'images\': "<tf.Tensor \'args_0:0\' shape=(None, 224, 224, 3) dtype=float64>", \'prompts\': "<tf.Tensor \'args_1:0\' shape=(None,) dtype=string>"}\n  • y={\'responses\': "<tf.Tensor \'args_2:0\' shape=(None,) dtype=string>"}\n  • sample_weight=None\n  • sequence_length=None'
```

**Expected behavior**
Since it's the official example, I would expect it to work out of the box

**Additional context**
This is my first time using Keras, so I might be missing something.

**Would you like to help us fix it?**
Sure.

**Comment by arrufat** [comment]
Ah, I found out the problem, the example is wrong, it should be:

```python
x = {
    "images": [image, image],
    "prompts": ["answer en Where is the cow standing?\n", "caption en\n"],
    "responses": ["beach", "A brown cow standing on a beach next to the ocean."],
}
pali_gemma_lm.fit(x=x, batch_size=2)
```
